### ISSUE TITLE
All dimensions are turned into islands.

### ISSUE THREAD

**Issue by Tokeli** [PixelatedW/islands#1]
v1.0.0 does not contain itself to the Overworld and turns every single dimension into a copy of the overworld with islands and water, both vanilla and modded.

**Comment by Tokeli** [comment]
Quite frankly I don't have the first clue how to do a PROPER pull request, and I couldn't get the mod to compile so was forced to put it into a fresh Forge mod and start from there so I'm just going to direct-link, [but I made a small change that enforces the worldtype on the overworld only, and tested it on the End and Nether but no modded worlds.](https://github.com/Tokeli/islands/blob/1.15.2/src/main/java/xyz/pixelated/islands/IslandWorldType.java)

**Comment by Wynd** [comment]
Made a pull request and merged it, thanks!
