### ISSUE TITLE
Wrong modloader tag "Fabric" for Islands - 1.16.5 - 1.4.1

### ISSUE THREAD

**Issue by pavog** [PixelatedW/islands#12]
You set the modloader tag "Fabric" for [Islands - 1.16.5 - 1.4.1](https://www.curseforge.com/minecraft/mc-mods/islands/files/3788840)
I think it's just a misclick / typo because this version does not run on Fabric, but on Forge.
Can you change it? 
Thanks! :-)

**Comment by Wynd** [comment]
Fixed. Thanks
