### ISSUE TITLE
islands_common.toml defaults all custom biome weight settings -- or is it just unclear for non-coders like me?

### ISSUE THREAD

**Issue by StygianEmperor** [PixelatedW/islands#4]
Sorry ahead of time if this is user error, I'm not much of a programmer.

**Version**
1.16.4
forge-1.16.4-35.1.15
Islands - 1.16.4 - 1.2.0

**Issue & steps to reproduce**
Each time I launch the game, every line below 30, `"minecraft:ocean" = 1.0` in the `islands_common.toml` config file gets reset to default. I'm somewhat suspicious that how I'm actually listing biomes is incorrect; I'm starting a new line for each biome where the format for every other list seems to use commas between each item, but I'm not sure if that would be the correct way either.

1. Hit enter key at the end of line 30 and add another biome to the list at an appropriate weight.
2. Start a new Islands-type Minecraft world. 
3. Exit Minecraft.
4. Check `islands_common.toml`.

A screenshot of my own `islands_common.toml` before launching the game:
![image](https://user-images.githubusercontent.com/75293860/103163229-0b5f7e80-47c1-11eb-9925-fb43badc26d0.png)

If this isn't the right way to do it, could you possibly add a second example biome to one or both of the current lists so others could see how a list of more than one is supposed to be formatted?

Also, is there some way the config examples could make it clear whether the biome weights accept more than one place after the decimal, such as 0.75?

**Comment by Wynd** [comment]
Thanks for the feedback I'll take a look at this, the format is ok so that's clearly not the problem and I'll also make the comments more specific.

**Comment by Wynd** [comment]
Fixed
