### ISSUE TITLE
Forge server crashed on start when level-type is set to "islands:islands"

### ISSUE THREAD

**Issue by mhostilis** [PixelatedW/islands#5]
Hi! So I've figured out that to use a modded world type on a server, you must put the mod ID and world type ID separated by a colon in the level-type field of the server.properties file. However, the server crashes on boot. I'm not using any other mods or plugins, just the Islands mod. I've attached the log file so you can better see what's going on.

[latest.log](https://github.com/PixelatedW/islands/files/5938672/latest.log)

**Comment by Wynd** [comment]
Fixed.
Use level-type:islands
