### ISSUE TITLE
Singleplayer world does not retain world generation settings.

### ISSUE THREAD

**Issue by mhostilis** [PixelatedW/islands#6]
Hello! I've tried using the mod on a singleplayer world, and it works as expected the first time you load in the world, but after leaving and rejoining the world, new chunks will be generated using default world generation. After messing around with NBTExplorer, I suspect this is because the world generation settings aren't being written to the level.dat file, since an Islands world does not contain the WorldGenSettings in the level.dat file. I've included two screenshots that shows this.

Default World NBT Data
![image](https://user-images.githubusercontent.com/78682023/107143446-b9029900-68fa-11eb-8ee0-667015c66099.png)

Islands World NBT Data
![image](https://user-images.githubusercontent.com/78682023/107143464-d3d50d80-68fa-11eb-95c9-29902d6ea7c9.png)

**Comment by Wynd** [comment]
Fixed ?
I've tested in all 3 versions (1.14, 1.15 and 1.16) both sp and mp and I wasn't able to replicate anymore so I'll just mark it as fixed for now.
